-->> [[ ꧁༒☬𝓒𝓻𝓮𝓪𝓽𝓸𝓻: 𝓓𝓲𝓪𝔁𝓲𝓾𝓶☬༒꧂ ]] <<--
--->> Name: StudioStyleGuideColor
 --->> Type: EnumItem
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--{{{ 𝓓𝓸𝓬𝓾𝓶𝓮𝓷𝓽𝓪𝓽𝓲𝓸𝓷:


--{{{ StudioStyleGuideColor:

--- @class Enum.StudioStyleGuideColor : EnumItem
--- @field MainBackground Enum.StudioStyleGuideColor @0
--- @field Titlebar Enum.StudioStyleGuideColor @1
--- @field Dropdown Enum.StudioStyleGuideColor @2
--- @field Tooltip Enum.StudioStyleGuideColor @3
--- @field Notification Enum.StudioStyleGuideColor @4
--- @field ScrollBar Enum.StudioStyleGuideColor @5
--- @field ScrollBarBackground Enum.StudioStyleGuideColor @6
--- @field TabBar Enum.StudioStyleGuideColor @7
--- @field Tab Enum.StudioStyleGuideColor @8
--- @field FilterButtonDefault Enum.StudioStyleGuideColor @9
--- @field FilterButtonHover Enum.StudioStyleGuideColor @10
--- @field FilterButtonChecked Enum.StudioStyleGuideColor @11
--- @field FilterButtonAccent Enum.StudioStyleGuideColor @12
--- @field FilterButtonBorder Enum.StudioStyleGuideColor @13
--- @field FilterButtonBorderAlt Enum.StudioStyleGuideColor @14
--- @field RibbonTab Enum.StudioStyleGuideColor @15
--- @field RibbonTabTopBar Enum.StudioStyleGuideColor @16
--- @field Button Enum.StudioStyleGuideColor @17
--- @field MainButton Enum.StudioStyleGuideColor @18
--- @field RibbonButton Enum.StudioStyleGuideColor @19
--- @field ViewPortBackground Enum.StudioStyleGuideColor @20
--- @field InputFieldBackground Enum.StudioStyleGuideColor @21
--- @field Item Enum.StudioStyleGuideColor @22
--- @field TableItem Enum.StudioStyleGuideColor @23
--- @field CategoryItem Enum.StudioStyleGuideColor @24
--- @field GameSettingsTableItem Enum.StudioStyleGuideColor @25
--- @field GameSettingsTooltip Enum.StudioStyleGuideColor @26
--- @field EmulatorBar Enum.StudioStyleGuideColor @27
--- @field EmulatorDropDown Enum.StudioStyleGuideColor @28
--- @field ColorPickerFrame Enum.StudioStyleGuideColor @29
--- @field CurrentMarker Enum.StudioStyleGuideColor @30
--- @field Border Enum.StudioStyleGuideColor @31
--- @field DropShadow Enum.StudioStyleGuideColor @32
--- @field Shadow Enum.StudioStyleGuideColor @33
--- @field Light Enum.StudioStyleGuideColor @34
--- @field Dark Enum.StudioStyleGuideColor @35
--- @field Mid Enum.StudioStyleGuideColor @36
--- @field MainText Enum.StudioStyleGuideColor @37
--- @field SubText Enum.StudioStyleGuideColor @38
--- @field TitlebarText Enum.StudioStyleGuideColor @39
--- @field BrightText Enum.StudioStyleGuideColor @40
--- @field DimmedText Enum.StudioStyleGuideColor @41
--- @field LinkText Enum.StudioStyleGuideColor @42
--- @field WarningText Enum.StudioStyleGuideColor @43
--- @field ErrorText Enum.StudioStyleGuideColor @44
--- @field InfoText Enum.StudioStyleGuideColor @45
--- @field SensitiveText Enum.StudioStyleGuideColor @46
--- @field ScriptSideWidget Enum.StudioStyleGuideColor @47
--- @field ScriptBackground Enum.StudioStyleGuideColor @48
--- @field ScriptText Enum.StudioStyleGuideColor @49
--- @field ScriptSelectionText Enum.StudioStyleGuideColor @50
--- @field ScriptSelectionBackground Enum.StudioStyleGuideColor @51
--- @field ScriptFindSelectionBackground Enum.StudioStyleGuideColor @52
--- @field ScriptMatchingWordSelectionBackground Enum.StudioStyleGuideColor @53
--- @field ScriptOperator Enum.StudioStyleGuideColor @54
--- @field ScriptNumber Enum.StudioStyleGuideColor @55
--- @field ScriptString Enum.StudioStyleGuideColor @56
--- @field ScriptComment Enum.StudioStyleGuideColor @57
--- @field ScriptKeyword Enum.StudioStyleGuideColor @58
--- @field ScriptBuiltInFunction Enum.StudioStyleGuideColor @59
--- @field ScriptWarning Enum.StudioStyleGuideColor @60
--- @field ScriptError Enum.StudioStyleGuideColor @61
--- @field ScriptWhitespace Enum.StudioStyleGuideColor @62
--- @field ScriptRuler Enum.StudioStyleGuideColor @63
--- @field DocViewCodeBackground Enum.StudioStyleGuideColor @64
--- @field DebuggerCurrentLine Enum.StudioStyleGuideColor @65
--- @field DebuggerErrorLine Enum.StudioStyleGuideColor @66
--- @field ScriptEditorCurrentLine Enum.StudioStyleGuideColor @105
--- @field DiffFilePathText Enum.StudioStyleGuideColor @67
--- @field DiffTextHunkInfo Enum.StudioStyleGuideColor @68
--- @field DiffTextNoChange Enum.StudioStyleGuideColor @69
--- @field DiffTextAddition Enum.StudioStyleGuideColor @70
--- @field DiffTextDeletion Enum.StudioStyleGuideColor @71
--- @field DiffTextSeparatorBackground Enum.StudioStyleGuideColor @72
--- @field DiffTextNoChangeBackground Enum.StudioStyleGuideColor @73
--- @field DiffTextAdditionBackground Enum.StudioStyleGuideColor @74
--- @field DiffTextDeletionBackground Enum.StudioStyleGuideColor @75
--- @field DiffLineNum Enum.StudioStyleGuideColor @76
--- @field DiffLineNumSeparatorBackground Enum.StudioStyleGuideColor @77
--- @field DiffLineNumNoChangeBackground Enum.StudioStyleGuideColor @78
--- @field DiffLineNumAdditionBackground Enum.StudioStyleGuideColor @79
--- @field DiffLineNumDeletionBackground Enum.StudioStyleGuideColor @80
--- @field DiffFilePathBackground Enum.StudioStyleGuideColor @81
--- @field DiffFilePathBorder Enum.StudioStyleGuideColor @82
--- @field ChatIncomingBgColor Enum.StudioStyleGuideColor @83
--- @field ChatIncomingTextColor Enum.StudioStyleGuideColor @84
--- @field ChatOutgoingBgColor Enum.StudioStyleGuideColor @85
--- @field ChatOutgoingTextColor Enum.StudioStyleGuideColor @86
--- @field ChatModeratedMessageColor Enum.StudioStyleGuideColor @87
--- @field Separator Enum.StudioStyleGuideColor @88
--- @field ButtonBorder Enum.StudioStyleGuideColor @89
--- @field ButtonText Enum.StudioStyleGuideColor @90
--- @field InputFieldBorder Enum.StudioStyleGuideColor @91
--- @field CheckedFieldBackground Enum.StudioStyleGuideColor @92
--- @field CheckedFieldBorder Enum.StudioStyleGuideColor @93
--- @field CheckedFieldIndicator Enum.StudioStyleGuideColor @94
--- @field HeaderSection Enum.StudioStyleGuideColor @95
--- @field Midlight Enum.StudioStyleGuideColor @96
--- @field StatusBar Enum.StudioStyleGuideColor @97
--- @field DialogButton Enum.StudioStyleGuideColor @98
--- @field DialogButtonText Enum.StudioStyleGuideColor @99
--- @field DialogButtonBorder Enum.StudioStyleGuideColor @100
--- @field DialogMainButton Enum.StudioStyleGuideColor @101
--- @field DialogMainButtonText Enum.StudioStyleGuideColor @102
--- @field InfoBarWarningBackground Enum.StudioStyleGuideColor @103
--- @field InfoBarWarningText Enum.StudioStyleGuideColor @104
--- @field ScriptMethod Enum.StudioStyleGuideColor @106
--- @field ScriptProperty Enum.StudioStyleGuideColor @107
--- @field ScriptNil Enum.StudioStyleGuideColor @108
--- @field ScriptBool Enum.StudioStyleGuideColor @109
--- @field ScriptFunction Enum.StudioStyleGuideColor @110
--- @field ScriptLocal Enum.StudioStyleGuideColor @111
--- @field ScriptSelf Enum.StudioStyleGuideColor @112
--- @field ScriptLuauKeyword Enum.StudioStyleGuideColor @113
--- @field ScriptFunctionName Enum.StudioStyleGuideColor @114
--- @field ScriptTodo Enum.StudioStyleGuideColor @115
--- @field ScriptBracket Enum.StudioStyleGuideColor @116
--- @field AttributeCog Enum.StudioStyleGuideColor @117

--}}} End of StudioStyleGuideColor;


--}}} End of 𝓓𝓸𝓬𝓾𝓶𝓮𝓷𝓽𝓪𝓽𝓲𝓸𝓷;