-->> [[ ꧁༒☬𝓒𝓻𝓮𝓪𝓽𝓸𝓻: 𝓓𝓲𝓪𝔁𝓲𝓾𝓶☬༒꧂ ]] <<--
--->> Name: BasePart
 --->> Type: PVInstance
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--{{{ 𝓓𝓸𝓬𝓾𝓶𝓮𝓷𝓽𝓪𝓽𝓲𝓸𝓷:


--{{{ BasePart:

--- @class BasePart : PVInstance
--- @field Anchored boolean
--- @field AssemblyAngularVelocity Vector3
--- @field AssemblyCenterOfMass Vector3
--- @field AssemblyLinearVelocity Vector3
--- @field AssemblyMass number
--- @field AssemblyRootPart BasePart
--- @field BackParamA number
--- @field BackParamB number
--- @field BackSurface Enum.SurfaceType
--- @field BackSurfaceInput Enum.InputType
--- @field BottomParamA number
--- @field BottomParamB number
--- @field BottomSurface Enum.SurfaceType
--- @field BottomSurfaceInput Enum.InputType
--- @field BrickColor BrickColor
--- @field CFrame CFrame
--- @field CanCollide boolean
--- @field CanQuery boolean
--- @field CanTouch boolean
--- @field CastShadow boolean
--- @field CenterOfMass Vector3
--- @field CollisionGroup string
--- @field CollisionGroupId number
--- @field Color Color3
--- @field CustomPhysicalProperties PhysicalProperties
--- @field Elasticity number
--- @field Friction number
--- @field FrontParamA number
--- @field FrontParamB number
--- @field FrontSurface Enum.SurfaceType
--- @field FrontSurfaceInput Enum.InputType
--- @field LeftParamA number
--- @field LeftParamB number
--- @field LeftSurface Enum.SurfaceType
--- @field LeftSurfaceInput Enum.InputType
--- @field LocalTransparencyModifier number
--- @field Locked boolean
--- @field Mass number
--- @field Massless boolean
--- @field Material Enum.Material
--- @field MaterialVariant string
--- @field Orientation Vector3
--- @field PivotOffset CFrame
--- @field Position Vector3
--- @field ReceiveAge number
--- @field Reflectance number
--- @field ResizeIncrement number
--- @field ResizeableFaces Faces
--- @field RightParamA number
--- @field RightParamB number
--- @field RightSurface Enum.SurfaceType
--- @field RightSurfaceInput Enum.InputType
--- @field RootPriority number
--- @field RotVelocity Vector3
--- @field Rotation Vector3
--- @field Size Vector3
--- @field SpecificGravity number
--- @field TopParamA number
--- @field TopParamB number
--- @field TopSurface Enum.SurfaceType
--- @field TopSurfaceInput Enum.InputType
--- @field Transparency number
--- @field Velocity Vector3
--- @field brickColor BrickColor
--- @field ApplyAngularImpulse fun( self : BasePart, impulse : Vector3 )
--- @field ApplyImpulse fun( self : BasePart, impulse : Vector3 )
--- @field ApplyImpulseAtPosition fun( self : BasePart, impulse : Vector3, position : Vector3 )
--- @field BreakJoints fun( self : BasePart )
--- @field CanCollideWith fun( self : BasePart, part : BasePart ) : boolean
--- @field CanSetNetworkOwnership fun( self : BasePart ) : table<any, any>
--- @field GetConnectedParts fun( self : BasePart, recursive : boolean ) : Instance[ ]|any[ ]
--- @field GetJoints fun( self : BasePart ) : Instance[ ]|any[ ]
--- @field GetMass fun( self : BasePart ) : number
--- @field GetNetworkOwner fun( self : BasePart ) : Instance
--- @field GetNetworkOwnershipAuto fun( self : BasePart ) : boolean
--- @field GetRenderCFrame fun( self : BasePart ) : CFrame
--- @field GetRootPart fun( self : BasePart ) : Instance
--- @field GetTouchingParts fun( self : BasePart ) : Instance[ ]|any[ ]
--- @field GetVelocityAtPosition fun( self : BasePart, position : Vector3 ) : Vector3
--- @field IsGrounded fun( self : BasePart ) : boolean
--- @field MakeJoints fun( self : BasePart )
--- @field Resize fun( self : BasePart, normalId : Enum.NormalId, deltaAmount : number ) : boolean
--- @field SetNetworkOwner fun( self : BasePart, playerInstance : Player )
--- @field SetNetworkOwnershipAuto fun( self : BasePart )
--- @field breakJoints fun( self : BasePart )
--- @field getMass fun( self : BasePart ) : number
--- @field makeJoints fun( self : BasePart )
--- @field resize fun( self : BasePart, normalId : Enum.NormalId, deltaAmount : number ) : boolean
--- @field SubtractAsync fun( self : BasePart, parts : Instance[ ]|any[ ], collisionfidelity : Enum.CollisionFidelity, renderFidelity : Enum.RenderFidelity ) : Instance
--- @field UnionAsync fun( self : BasePart, parts : Instance[ ]|any[ ], collisionfidelity : Enum.CollisionFidelity, renderFidelity : Enum.RenderFidelity ) : Instance
--- @field LocalSimulationTouched RBXScriptSignal@fun( part : BasePart )
--- @field OutfitChanged RBXScriptSignal@fun( )
--- @field StoppedTouching RBXScriptSignal@fun( otherPart : BasePart )
--- @field TouchEnded RBXScriptSignal@fun( otherPart : BasePart )
--- @field Touched RBXScriptSignal@fun( otherPart : BasePart )

--}}} End of BasePart;


--}}} End of 𝓓𝓸𝓬𝓾𝓶𝓮𝓷𝓽𝓪𝓽𝓲𝓸𝓷;