-->> [[ ꧁༒☬𝓒𝓻𝓮𝓪𝓽𝓸𝓻: 𝓓𝓲𝓪𝔁𝓲𝓾𝓶☬༒꧂ ]] <<--
--->> Name: Studio
 --->> Type: Instance
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--{{{ 𝓓𝓸𝓬𝓾𝓶𝓮𝓷𝓽𝓪𝓽𝓲𝓸𝓷:


--{{{ Studio:

--- @class Studio : Instance
--- @field "TODO"Color Color3
--- @field "function"Color Color3
--- @field "local"Color Color3
--- @field "nil"Color Color3
--- @field "self"Color Color3
--- @field ActiveColor Color3
--- @field ActiveHoverOverColor Color3
--- @field AlwaysSaveScriptChanges boolean
--- @field AnimateHoverOver boolean
--- @field AutoCleanEmptyLine boolean
--- @field AutoClosingBrackets boolean
--- @field AutoClosingQuotes boolean
--- @field AutoIndentRule Enum.AutoIndentRule
--- @field Auto-RecoveryEnabled boolean
--- @field Auto-RecoveryInterval(Minutes) number
--- @field Auto-RecoveryPath QDir
--- @field BackgroundColor Color3
--- @field BasicObjectsDisplayMode Enum.ListDisplayMode
--- @field BoolColor Color3
--- @field BracketColor Color3
--- @field Built-inFunctionColor Color3
--- @field CameraMouseWheelSpeed number
--- @field CameraPanSpeed number
--- @field CameraShiftSpeed number
--- @field CameraSpeed number
--- @field CameraZoomtoMousePosition boolean
--- @field ClearOutputOnStart boolean
--- @field CommandBarLocalState boolean
--- @field CommentColor Color3
--- @field CurrentLineHighlightColor Color3
--- @field DebuggerCurrentLineColor Color3
--- @field DebuggerErrorLineColor Color3
--- @field DefaultScriptFileDir QDir
--- @field DeprecatedObjectsShown boolean
--- @field DisplayLanguage string
--- @field DocViewCodeBackgroundColor Color3
--- @field DragMultiplePartsAsSinglePart boolean
--- @field EnableAutocomplete boolean
--- @field EnableAutocompleteDocView boolean
--- @field EnableCoreScriptDebugger boolean
--- @field EnableHttpSandboxing boolean
--- @field EnableInternalBetaFeatures boolean
--- @field EnableInternalFeatures boolean
--- @field EnableScriptAnalysis boolean
--- @field EnableScrollbarMarkers boolean
--- @field EnableSignatureHelp boolean
--- @field EnableSignatureHelpDocView boolean
--- @field EnableTemporaryTabs boolean
--- @field EnableTemporaryTabsInExplorer boolean
--- @field EnableTypeHover boolean
--- @field EnableOnTypeAutocomplete boolean
--- @field ErrorColor Color3
--- @field FindSelectionBackgroundColor Color3
--- @field Font QFont
--- @field FormatOnPaste boolean
--- @field FormatOnType boolean
--- @field FunctionNameColor Color3
--- @field HighlightCurrentLine boolean
--- @field HighlightOccurances boolean
--- @field HoverAnimateSpeed Enum.HoverAnimateSpeed
--- @field HoverBoxThickness number
--- @field HoverOverColor Color3
--- @field IconOverrideDir QDir
--- @field IndentUsingSpaces boolean
--- @field KeywordColor Color3
--- @field LineThickness number
--- @field LocalAssetsFolder QDir
--- @field LuaDebuggerEnabled boolean
--- @field LuaDebuggerEnabledAtStartup boolean
--- @field LuauKeywordColor Color3
--- @field MainVolume number
--- @field MatchingWordBackgroundColor Color3
--- @field MaximumOutputLines number
--- @field MenuItemBackgroundColor Color3
--- @field MethodColor Color3
--- @field NumberColor Color3
--- @field OnlyPlayAudiofromWindowinFocus boolean
--- @field OperatorColor Color3
--- @field OutputFont QFont
--- @field OutputLayoutMode Enum.OutputLayoutMode
--- @field PermissionLevelShown Enum.PermissionLevelShown
--- @field PhysicalDraggersSelectScopeByDefault boolean
--- @field PivotSnapToGeometryColor Color3
--- @field PluginDebuggingEnabled boolean
--- @field PluginsDir QDir
--- @field PrimaryTextColor Color3
--- @field PropertyColor Color3
--- @field RenderThrottlePercentage number
--- @field RespectStudioshortcutswhengamehasfocus boolean
--- @field RulerColor Color3
--- @field Rulers string
--- @field RuntimeUndoBehavior Enum.RuntimeUndoBehavior
--- @field ScriptEditorColorPreset Enum.StudioScriptEditorColorPresets
--- @field ScriptEditorScrollbarBackgroundColor Color3
--- @field ScriptEditorScrollbarHandleColor Color3
--- @field ScriptEditorMenuBorderColor Color3
--- @field ScriptEditorShouldShowPluginMethods boolean
--- @field ScriptTimeoutLength number
--- @field ScrollPastLastLine boolean
--- @field SearchContentForCoreScripts boolean
--- @field SecondaryTextColor Color3
--- @field SelectColor Color3
--- @field Select/HoverColor Color3
--- @field SelectedMenuItemBackgroundColor Color3
--- @field SelectedTextColor Color3
--- @field SelectionBackgroundColor Color3
--- @field SelectionColor Color3
--- @field SelectionHighlightThickness number
--- @field ServerAudioBehavior Enum.ServerAudioBehavior
--- @field SetPivotofImportedParts boolean
--- @field ShowCoreGUIinExplorerwhilePlaying boolean
--- @field ShowDeploymentWarnings boolean
--- @field ShowDiagnosticsBar boolean
--- @field ShowFileSyncService boolean
--- @field ShowHiddenObjectsinExplorer boolean
--- @field ShowHoverOver boolean
--- @field ShowLightGuides boolean
--- @field ShowNavigationLabels boolean
--- @field ShowNavigationMesh boolean
--- @field ShowPathfindingLinks boolean
--- @field ShowPluginGUIServiceinExplorer boolean
--- @field ShowQTwarningsinoutput boolean
--- @field ShowWhitespace boolean
--- @field ShowplusbuttononhoverinExplorer boolean
--- @field ShowCorePackagesInExplorer boolean
--- @field SkipClosingBracketsandQuotes boolean
--- @field StringColor Color3
--- @field TabWidth number
--- @field TextColor Color3
--- @field TextWrapping boolean
--- @field Theme Instance
--- @field UITheme Enum.UITheme
--- @field UseBoundingBoxMoveHandles boolean
--- @field WarningColor Color3
--- @field WhitespaceColor Color3
--- @field GetAvailableThemes fun( self : Studio ) : table<number, any>
--- @field ThemeChanged RBXScriptSignal@fun( )

--}}} End of Studio;


--}}} End of 𝓓𝓸𝓬𝓾𝓶𝓮𝓷𝓽𝓪𝓽𝓲𝓸𝓷;